# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:
  # Global
  ap_vm_image: ubuntu-20.04

  namespace: mlopsv2 #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 01
  location: eastus2
  environment: prod
  enable_aml_computecluster: true
  enable_monitoring: true

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: qt-mlops-rg
  aml_workspace: proddemoml01
  application_insights: aiproddemoml01
  key_vault: kvproddemoml01
  container_registry: crproddemoml01
  storage_account: stproddemoml01

  # For terraform reference
  terraform_version: 1.3.6
  terraform_workingdir: infrastructure
  terraform_st_location: $(location)
  terraform_st_resource_group: qt-mlops-rg
  terraform_st_storage_account: stproddemoml01tf
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
