# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Dev environment
variables:
  # Global
  ap_vm_image: ubuntu-20.04

  namespace: mlopsv2 #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 01
  location: eastus2
  environment: dev
  enable_aml_computecluster: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Dev
  ado_service_connection_aml_ws: Azure-ARM-Dev

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: qt-mlops-rg
  aml_workspace: demoml01
  application_insights: aidemoml01
  key_vault: kvdemoml01
  container_registry: crdemoml01
  storage_account: stdemoml01

  # For terraform reference
  terraform_version: 1.3.6
  terraform_workingdir: infrastructure
  terraform_st_location: $(location)
  terraform_st_resource_group: qt-mlops-rg
  terraform_st_storage_account: stdemoml01tf
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
