# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
- name: deployment_name
  type: string
- name: deployment_description
  type: string
- name: endpoint_name
  type: string
- name: model_path
  type: string
- name: compute
  type: string


steps:
    
- task: AzureCLI@2
  displayName: Creating batch deployment
  inputs:
    azureSubscription: $(ado_service_connection_aml_ws)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      python templates/src/python-sdk-v2/create_batch_deployment.py \
        --deployment_name "${{parameters.deployment_name}}" \
        --description "${{parameters.deployment_description}}" \
        --endpoint_name "${{parameters.endpoint_name}}" \
        --model_path "${{parameters.model_path}}" \
        --compute "${{parameters.compute}}" \
