channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.12.0
  - pip
  - pip:
      - azureml-mlflow==1.58.0
      - azure-ai-ml==1.21.1
      - pyarrow==17.0.0
      - scikit-learn==1.5.2
      - pandas==2.2.3
      - joblib==1.4.2
      - matplotlib==3.9.2
      - mlflow==2.17.0
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector