name: 1. Train Model

on:
  workflow_dispatch:

jobs:
  parse-yaml:
    runs-on: ubuntu-latest
    outputs:
      location: ${{ steps.read-yaml.outputs.location }}
      resource_group: ${{ steps.read-yaml.outputs.resource_group }}
      aml_workspace: ${{ steps.read-yaml.outputs.aml_workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Read environment variables from the YAML config file (dev or prod)
        id: read-yaml
        run: python ./github/workflows/scripts/parse_yaml.py config-infra-dev.yml

      - name: Use environment variables in another job
        run: echo "The VM image is ${{ steps.read-yaml.outputs.ap_vm_image }} located in ${{ steps.read-yaml.outputs.location }} with postfix ${{ steps.read-yaml.outputs.postfix }}"

  # Step 1: Register environments
  register-environment:
    needs: parse-yaml
    uses: ./github/workflows/templates/register-environment.yml@dev
    with:
      resource_group: ${{ needs.parse-yaml.outputs.resource_group }}
      workspace_name: ${{ needs.parse-yaml.outputs.aml_workspace }}
      environment_file: ./mlops/azureml/train/train-env.yml
      conda_file: data-science/environment/train-conda.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  
  #Step 2: Register the dataset
  register-dataset:
    needs: parse-yaml
    uses: ./github/workflows/templates/register-dataset.yml@dev
    with:
      resource_group: ${{ needs.parse-yaml.outputs.resource_group }}
      workspace_name: ${{ needs.parse-yaml.outputs.aml_workspace }}
      name: taxi-data
      data_file: ./mlops/azureml/train/data.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  
  #Step 3: Create a compute instance
  create-compute:
    needs: parse-yaml
    uses: ./github/workflows/templates/create-compute.yml@dev
    with:
      cluster_name: cpu-cluster
      size: Standard_DS3_v2
      min_instances: 0
      max_instances: 4
      cluster_tier: low_priority
      resource_group: ${{ needs.parse-yaml.outputs.resource_group }}
      workspace_name: ${{ needs.parse-yaml.outputs.aml_workspace }}
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}

  #Step 4: Train the model
  run-model-training-pipeline:
    needs: [parse-yaml, register-environment, register-dataset, create-compute]
    uses: ./github/workflows/templates/run-pipeline.yml@dev
    with:
      resource_group: ${{ needs.parse-yaml.outputs.resource_group }}
      workspace_name: ${{ needs.parse-yaml.outputs.aml_workspace }}
      parameters-file: ./mlops/azureml/train/pipeline.yml
      job-name: test
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}